spring.application.name=trangpt

spring.datasource.url=jdbc:postgresql://localhost:5433/demo_app
spring.datasource.username=postgres
spring.datasource.password=trangtrang
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://id.smartsolutionvn.com.vn/realms/ssvn
app.security.super-admin-username=ssvn
app.security.super-admin-roles=Admin Ssvn,SUPER_ADMIN
app.security.local-jwt-secret=${LOCAL_JWT_SECRET:trangpt-local-jwt-secret-please-change-32bytes}
app.security.local-jwt-issuer=trangpt-app

keycloak.token-uri=https://id.smartsolutionvn.com.vn/realms/ssvn/protocol/openid-connect/token
keycloak.client-id=ssvn-platform-client-id
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:cn7crCkSWaXBcmWzDCxF2S2qq9jZ9hLN}
